# Generated by Django 5.2.17 on 2026-09-26 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_phase2_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='May be 0 for BORROW or EXCHANGE listings.', max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like new'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], db_index=True, max_length=20)),
                ('transaction_type', models.CharField(choices=[('SELL', 'Sell'), ('BORROW', 'Borrow'), ('EXCHANGE', 'Exchange')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('BORROWED', 'Borrowed'), ('EXCHANGED', 'Exchanged'), ('CLOSED', 'Closed'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('preferred_exchange_item', models.CharField(blank=True, help_text='Preferred item or description when transaction_type is EXCHANGE.', max_length=255)),
                ('exchange_description', models.TextField(blank=True, help_text='Additional exchange details when transaction_type is EXCHANGE.')),
                ('removed_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'transaction_type'], name='listings_status_c27b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='listings_categor_7f7673_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='listings_seller__9c3ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_created_4615f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='listing_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transaction_type', 'EXCHANGE'), _negated=True), models.Q(('preferred_exchange_item', ''), _negated=True), models.Q(('exchange_description', ''), _negated=True), _connector='OR'), name='listing_exchange_requires_preference_or_description'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_primary'], name='listing_ima_listing_7b284b_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('listing',), name='unique_primary_image_per_listing'),
        ),
    ]
